### ISSUE TITLE
Receipt Conflict between heater pipe and techreborn copper wire

### ISSUE THREAD

**Issue by x-0D** [NivOridocs/heater#3]

**Comment by NivOridocs** [comment]
For recipe conflicts, I usually use [Polymorph](https://modrinth.com/mod/polymorph). See if it solves your problems, too.

Otherwise, you'll have to create a data pack and overwrite either the Heat Pipe or the Copper Wire recipes. There are already plenty of online resources that explain how to do it.

I surely will not change my mod's recipe. There are, after all, only a finite number of combinations on the crafting grid, and whatever recipe I choose will eventually conflict with some other mod, making every "fix" on my part ultimately pointless.
