### ISSUE TITLE
Mod Integration: Energy Based Heater

### ISSUE THREAD

**Issue by JasdanVM** [NivOridocs/heater#6]
I'd love it if you added an electrical heater that consumed energy for the heat generation, so having lots of energy get another use on the pretty limited Fabric energy ecosystem.
I have other ideas regarding electrical Thermoregulators, but this one addition would be huge.

**Comment by NivOridocs** [comment]
I have already considered bridging Heater and the Energy API in some way. Still, I've never implemented anything and probably never will for one simple reason: I don't want to make Heater too bloated with features. I like my mods to do only one thing, but well.

That said, I'm thinking of extracting part of Heater (namely, the third-party furnace compatibility feature) to a new API that everyone can use and developing another mod (a Heater companion mod, I might say) that makes every Heater-compatible furnace (Heater's heater included) able to at least receiving heat as energy from the Energy API. This last mod should do what you're asking and more.

Since I have yet to write a single line of code about all of this, any suggestion is much welcome.

Spoiler: I'm already moving to Minecraft 1.21, so every new implementation will be for that version.

(Though, now I'm curious about these electrical Thermoregulators of yours...)

**Comment by JasdanVM** [comment]
Well, the ideas I had for Thermoregulators are as follow:
The addition of blocks that consume energy and in turn generate heat or cold.
The heaters would be compatible with Farmer's Delight, cooking food faster when under a Skillet than regular fire, and they'd be able to replace Blaze Burners from Create (except for their Super-Heated state).
Coolers would turn water over them into Ice in any biome, and when boosted up, they'd create Packed Ice.
This blocks could get electrical fans attached, (but would also work with the airflow of Create's Encased Fans) that alter the temperature of enclosed spaces, the more Heater/Cooler blocks used and the more power consumed, the bigger the area that can be transformed, useful for mods such as Scorcheful and Frostiful (and other temperature survival mods) for overridding the biome conditions you are in.
There could also be integration with mods that simulate rain, such as Create: Slice and Dice for submerging a build into an eternal Snowstorm and generating snow.
Hyper-heated rooms would have a chance of setting wood and mobs on fire, and would simulate the Nether's water evaporation effect.
Super-cooled rooms would apply slowness and a chance to give powdered snow effect to mobs, and trap dropped items in ice if [Rare Ice](https://modrinth.com/mod/rare-ice) is installed.
And of course they would damage and freeze mobs directly standing on them.

**Comment by NivOridocs** [comment]
As planned, I developed a couple of mods ([Burning](https://github.com/NivOridocs/burning) and [Burning Energy](https://github.com/NivOridocs/burning-energy), which are also on Modrinth), which are, respectively, the API and the "companion mod" I had anticipated.

Go check them out if you're interested.

And with this, I'm closing this issue.

***

P.S.: I didn't understand whether you want to develop these Thermoregulators yourself, in which case, godspeed, and I hope to try them one day, or if you expect me to develop them, in which case, sorry, I won't.
